# Generated by Django 4.2.21 on 2025-06-04 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0007_chargingconnector_available_quantity_and_more'),
        ('ocpp_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_alter_paymentmethod_method_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRPaymentSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_type', models.CharField(choices=[('amount', 'Fixed Amount'), ('kwh', 'Kilowatt Hours')], max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('kwh_requested', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('calculated_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('payment_initiated', 'Payment Initiated'), ('payment_completed', 'Payment Completed'), ('charging_started', 'Charging Started'), ('charging_completed', 'Charging Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charging_session', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ocpp_integration.chargingsession')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_sessions', to='charging_stations.chargingconnector')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payment_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
