# Generated by Django 4.2.21 on 2025-06-06 03:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0009_stationreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0003_qrpaymentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleChargingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=64, unique=True)),
                ('payment_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('id_tag', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('started', 'Started'), ('charging', 'Charging'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='started', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('energy_consumed_kwh', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('max_power_kw', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_charging_sessions', to='charging_stations.chargingconnector')),
                ('qr_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charging_sessions', to='payments.qrpaymentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_charging_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Simple Charging Session',
                'verbose_name_plural': 'Simple Charging Sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
