# Generated by Django 4.2.21 on 2025-06-07 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_simplechargingsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpaymentsession',
            name='simple_charging_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_session_link', to='payments.simplechargingsession'),
        ),
        migrations.AddField(
            model_name='simplechargingsession',
            name='cost_per_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='simplechargingsession',
            name='energy_delivered_kwh',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='simplechargingsession',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='simplechargingsession',
            name='id_tag',
            field=models.CharField(blank=True, default='mobile_app', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='simplechargingsession',
            name='qr_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simple_charging_sessions', to='payments.qrpaymentsession'),
        ),
    ]
