# Generated by Django 4.2.21 on 2025-06-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_qrpaymentsession_simple_charging_session_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymentsession",
            name="user",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="payment_method",
        ),
        migrations.DeleteModel(
            name="PaymentMethod",
        ),
        migrations.DeleteModel(
            name="PaymentSession",
        ),
    ]
