services:
  # Backend service
  - type: web
    name: mengedmate-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mengedmate.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: mengedmate-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://mengedmate-frontend.onrender.com"
      - key: FRONTEND_URL
        value: "https://mengedmate-frontend.onrender.com"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false

  # Frontend service
  - type: web
    name: mengedmate-frontend
    env: static
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "./frontend/build"
    envVars:
      - key: REACT_APP_API_URL
        value: "https://mengedmate-backend.onrender.com"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: mengedmate-db
    plan: free
