services:
  # Combined backend and frontend service
  - type: web
    name: mengedmate
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn mengedmate.wsgi:application"
    # Ensure templates directory is included in the build
    buildFilter:
      paths:
        - templates/**
        - static/**
        - media/**
        - "*.py"
        - "*.sh"
        - "*.txt"
        - "*.yaml"
        - "*.json"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: mengedmate-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://mengedmate.onrender.com"
      - key: FRONTEND_URL
        value: "https://mengedmate.onrender.com"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
    # Ensure the database is created before the service starts
    dependsOn:
      - mengedmate-db

databases:
  - name: mengedmate-db
    plan: free
    # Ensure the database is created with the correct settings
    ipAllowList: [] # only allow internal connections
