services:
  # Combined service for both frontend and backend
  - type: web
    name: mengedmate
    env: python
    plan: free
    # Option 1: Use build script
    buildCommand: "bash ./build_combined.sh"
    startCommand: "gunicorn mengedmate.wsgi:application"
    # Option 2: Uncomment to use Docker instead
    # dockerfilePath: ./Dockerfile
    # dockerCommand: gunicorn mengedmate.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "mengedmate.onrender.com,.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: mengedmate-db
          property: connectionString
      - key: CORS_ALLOWED_ORIGINS
        value: "https://mengedmate.onrender.com,http://localhost:3000"
      - key: FRONTEND_URL
        value: "https://mengedmate.onrender.com"
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
    # Ensure the database is created before the service starts
    dependsOn:
      - mengedmate-db

databases:
  - name: mengedmate-db
    plan: free
    # Ensure the database is created with the correct settings
    ipAllowList: [] # only allow internal connections
