services:
  - type: web
    name: mengedmate-backend
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn mengedmate.wsgi:application
    plan: free
    envVars:
      - key: SECRET_KEY
        value: "<your-django-secret-key>"
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "<your-backend-domain>,.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://<your-frontend-domain>.onrender.com"
      - key: FRONTEND_URL
        value: "https://<your-frontend-domain>.onrender.com"
      - key: EMAIL_HOST_USER
        value: "<your-gmail-address>"
      - key: EMAIL_HOST_PASSWORD
        value: "<your-gmail-app-password>"
    autoDeploy: true

  - type: static
    name: mengedmate-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://<your-backend-domain>.onrender.com"
    autoDeploy: true 