# Generated by Django 4.2.21 on 2025-05-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chargingconnector",
            old_name="power_output",
            new_name="power_kw",
        ),
        migrations.RemoveField(
            model_name="chargingstation",
            name="amenities",
        ),
        migrations.AddField(
            model_name="chargingconnector",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chargingconnector",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="has_restaurant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="has_restroom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="has_shopping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="has_wifi",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stationowner",
            name="business_document",
            field=models.FileField(
                blank=True, null=True, upload_to="station_owner_docs/business_docs/"
            ),
        ),
        migrations.AddField(
            model_name="stationowner",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="stationowner",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
