# Generated by Django 4.2.21 on 2025-05-17 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "charging_stations",
            "0002_rename_power_output_chargingconnector_power_kw_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingstation",
            name="available_connectors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="is_operational",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="marker_icon",
            field=models.CharField(
                blank=True, default="default", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="price_range",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="rating",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="rating_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chargingstation",
            name="total_connectors",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="FavoriteStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="charging_stations.chargingstation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_stations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "station")},
            },
        ),
    ]
