# Generated by Django 4.2.21 on 2025-05-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0003_chargingstation_available_connectors_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargingstation",
            name="status",
            field=models.CharField(
                choices=[
                    ("operational", "Operational"),
                    ("under_maintenance", "Under Maintenance"),
                    ("closed", "Closed"),
                    ("coming_soon", "Coming Soon"),
                ],
                default="operational",
                max_length=20,
            ),
        ),
    ]
