# Generated by Django 4.2.21 on 2025-05-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0004_chargingstation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingconnector',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('out_of_order', 'Out of Order'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
