# Generated by Django 4.2.21 on 2025-05-31 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0005_chargingconnector_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargingstation',
            name='is_operational',
        ),
    ]
