# Generated by Django 4.2.21 on 2025-06-04 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0006_remove_is_operational'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingconnector',
            name='available_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='chargingconnector',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chargingconnector',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='chargingconnector',
            name='qr_code_token',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='chargingconnector',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
