# Generated by Django 4.2.21 on 2025-06-08 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0009_stationreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("booking_confirmed", "Booking Confirmed"),
                            ("payment_received", "Payment Received"),
                            ("session_started", "Session Started"),
                            ("session_completed", "Session Completed"),
                            ("maintenance_required", "Maintenance Required"),
                            ("station_offline", "Station Offline"),
                            ("low_balance", "Low Balance"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("email_body", models.TextField()),
                ("sms_body", models.TextField(max_length=160)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
            },
        ),
        migrations.AlterField(
            model_name="appcontent",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("about", "About evmeri"),
                    ("privacy_policy", "Privacy Policy"),
                    ("terms_of_service", "Terms of Service"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="StationOwnerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_pricing_per_kwh",
                    models.DecimalField(decimal_places=2, default=5.5, max_digits=6),
                ),
                ("auto_accept_bookings", models.BooleanField(default=True)),
                ("max_session_duration_hours", models.PositiveIntegerField(default=4)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("booking_notifications", models.BooleanField(default=True)),
                ("payment_notifications", models.BooleanField(default=True)),
                ("maintenance_alerts", models.BooleanField(default=True)),
                ("marketing_emails", models.BooleanField(default=False)),
                ("station_updates", models.BooleanField(default=True)),
                ("brand_color", models.CharField(default="#3B82F6", max_length=7)),
                ("logo_url", models.URLField(blank=True, null=True)),
                ("custom_welcome_message", models.TextField(blank=True, null=True)),
                ("display_company_info", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="charging_stations.stationowner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Station Owner Settings",
                "verbose_name_plural": "Station Owner Settings",
            },
        ),
    ]
