# Generated by Django 4.2.21 on 2025-06-10 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0011_reviewreply"),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("bank_account", "Bank Account"),
                            ("card", "Credit/Debit Card"),
                            ("mobile_money", "Mobile Money"),
                            ("paypal", "PayPal"),
                        ],
                        default="bank_account",
                        max_length=20,
                    ),
                ),
                ("account_holder_name", models.CharField(blank=True, max_length=255)),
                ("bank_name", models.CharField(blank=True, max_length=255)),
                ("account_number", models.CharField(blank=True, max_length=50)),
                ("routing_number", models.CharField(blank=True, max_length=20)),
                ("swift_code", models.CharField(blank=True, max_length=20)),
                ("card_number", models.CharField(blank=True, max_length=20)),
                ("card_type", models.CharField(blank=True, max_length=20)),
                ("expiry_month", models.CharField(blank=True, max_length=2)),
                ("expiry_year", models.CharField(blank=True, max_length=4)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("provider", models.CharField(blank=True, max_length=50)),
                ("paypal_email", models.EmailField(blank=True, max_length=254)),
                ("is_default", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station_owner",
                    models.ForeignKey(
                        help_text="Station owner who owns this payout method",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payout_methods",
                        to="charging_stations.stationowner",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["station_owner", "-created_at"],
                        name="charging_st_station_c65335_idx",
                    ),
                    models.Index(
                        fields=["station_owner", "is_default"],
                        name="charging_st_station_9da39c_idx",
                    ),
                    models.Index(
                        fields=["method_type", "is_active"],
                        name="charging_st_method__0784e6_idx",
                    ),
                ],
            },
        ),
    ]
