# Generated by Django 4.2.21 on 2025-06-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0012_payoutmethod"),
    ]

    operations = []
