# Generated by Django 4.2.21 on 2025-06-14 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("charging_stations", "0013_auto_20250610_0417"),
    ]

    operations = [
        migrations.CreateModel(
            name="WithdrawalRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, help_text="Amount to withdraw", max_digits=10
                    ),
                ),
                ("currency", models.CharField(default="ETB", max_length=3)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Admin who approved/rejected this withdrawal",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payout_method",
                    models.ForeignKey(
                        help_text="Payment method for the withdrawal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawals",
                        to="charging_stations.payoutmethod",
                    ),
                ),
                (
                    "station_owner",
                    models.ForeignKey(
                        help_text="Station owner requesting the withdrawal",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="withdrawal_requests",
                        to="charging_stations.stationowner",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["station_owner", "-created_at"],
                        name="charging_st_station_a8591b_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="charging_st_status_1dcead_idx",
                    ),
                    models.Index(
                        fields=["reference_number"],
                        name="charging_st_referen_beb3e1_idx",
                    ),
                ],
            },
        ),
    ]
