# Generated by Django 4.2.21 on 2025-06-14 14:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0014_withdrawalrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingconnector",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
