# Generated by Django 4.2.27 on 2026-01-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("charging_stations", "0014_withdrawalrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chargingconnector",
            name="qr_code_image",
            field=models.TextField(
                blank=True, help_text="Base64 encoded QR code image", null=True
            ),
        ),
        migrations.AlterField(
            model_name="chargingstation",
            name="main_image",
            field=models.TextField(
                blank=True, help_text="Base64 encoded main station image", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stationimage",
            name="image",
            field=models.TextField(help_text="Base64 encoded station image"),
        ),
        migrations.AlterField(
            model_name="stationowner",
            name="business_document",
            field=models.TextField(
                blank=True, help_text="Base64 encoded business document", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stationowner",
            name="business_license",
            field=models.TextField(
                blank=True, help_text="Base64 encoded business license", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stationowner",
            name="id_proof",
            field=models.TextField(
                blank=True, help_text="Base64 encoded ID proof", null=True
            ),
        ),
        migrations.AlterField(
            model_name="stationowner",
            name="utility_bill",
            field=models.TextField(
                blank=True, help_text="Base64 encoded utility bill", null=True
            ),
        ),
    ]
