# Generated by Django 4.2.27 on 2026-01-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="screenshot",
            field=models.TextField(
                blank=True, help_text="Base64 encoded screenshot", null=True
            ),
        ),
    ]
