# Generated by Django 4.2.21 on 2025-06-06 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('endpoint', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('request_example', models.TextField(blank=True)),
                ('response_example', models.TextField(blank=True)),
                ('authentication_required', models.BooleanField(default=True)),
                ('category', models.CharField(default='General', max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Endpoint',
                'verbose_name_plural': 'API Endpoints',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentationSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('section_type', models.CharField(choices=[('overview', 'System Overview'), ('architecture', 'System Architecture'), ('tech_stack', 'Technology Stack'), ('deployment', 'Deployment Instructions'), ('database', 'Database Design'), ('security', 'Security & Authentication'), ('integrations', 'Third-Party Integrations'), ('scaling', 'Scaling & Performance'), ('api_docs', 'API Documentation'), ('troubleshooting', 'Troubleshooting')], max_length=20, unique=True)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Documentation Section',
                'verbose_name_plural': 'Documentation Sections',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('component_type', models.CharField(choices=[('backend', 'Backend Framework'), ('frontend', 'Frontend Framework'), ('database', 'Database'), ('payment', 'Payment Gateway'), ('deployment', 'Deployment Platform'), ('monitoring', 'Monitoring Tool'), ('other', 'Other')], max_length=20)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField()),
                ('purpose', models.TextField()),
                ('documentation_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Technology Component',
                'verbose_name_plural': 'Technology Components',
                'ordering': ['component_type', 'name'],
            },
        ),
    ]
