# Generated by Django 4.2.21 on 2025-05-21 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_add_notification_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Vehicle name or nickname", max_length=100
                    ),
                ),
                ("make", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.PositiveIntegerField()),
                (
                    "battery_capacity_kwh",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                (
                    "connector_type",
                    models.CharField(
                        choices=[
                            ("type1", "Type 1 (J1772)"),
                            ("type2", "Type 2 (Mennekes)"),
                            ("ccs1", "CCS Combo 1"),
                            ("ccs2", "CCS Combo 2"),
                            ("chademo", "CHAdeMO"),
                            ("tesla", "Tesla"),
                            ("other", "Other"),
                            ("none", "None"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
