# Generated by Django 4.2.21 on 2025-05-27 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_vehicle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-is_primary', '-last_used_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='customuser',
            name='active_vehicle',
            field=models.ForeignKey(blank=True, help_text='Currently selected vehicle for recommendations', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_users', to='authentication.vehicle'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='efficiency_kwh_per_100km',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Energy consumption in kWh per 100km', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='estimated_range_km',
            field=models.PositiveIntegerField(blank=True, help_text='Estimated range in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Vehicle is actively used'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_charging_speed_kw',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum charging speed in kW', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='notes',
            field=models.TextField(blank=True, help_text='Personal notes about the vehicle', null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='preferred_charging_speed',
            field=models.CharField(blank=True, choices=[('slow', 'Slow (3-7 kW)'), ('fast', 'Fast (7-22 kW)'), ('rapid', 'Rapid (22-50 kW)'), ('ultra_rapid', 'Ultra Rapid (50+ kW)')], default='fast', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_charging_sessions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='total_energy_charged_kwh',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='usable_battery_kwh',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Usable battery capacity in kWh', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='battery_capacity_kwh',
            field=models.DecimalField(decimal_places=2, help_text='Total battery capacity in kWh', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Primary vehicle (shown first in lists)'),
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(condition=models.Q(('license_plate__isnull', False)), fields=('user', 'license_plate'), name='unique_license_plate_per_user'),
        ),
    ]
