# Generated by Django 4.2.21 on 2025-06-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_social_auth"),
        ("authentication", "0007_customuser_telegram_auth_date_and_more"),
    ]

    operations = []
