# Generated by Django 4.2.27 on 2026-01-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_merge_20250616_0842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profile_picture",
            field=models.TextField(
                blank=True, help_text="Base64 encoded profile picture", null=True
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_image",
            field=models.TextField(
                blank=True, help_text="Base64 encoded vehicle image", null=True
            ),
        ),
    ]
